//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.ServiceModel.Channels;
using System.Xml;
using System;
using System.IO;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Caiso.WebServices.Security
{

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/mrtu/soa/schemas/2005/09/attachmenthash")]
	[System.Xml.Serialization.XmlRootAttribute("attachmentHash", Namespace = "http://www.caiso.com/mrtu/soa/schemas/2005/09/attachmenthash", IsNullable = false)]
	public partial class attachmentHashType : MessageHeader
	{

		private string hashValueField;

		/// <remarks/>
		public string hashValue
		{
			get
			{
				return this.hashValueField;
			}
			set
			{
				this.hashValueField = value;
			}
		}

		protected override void OnWriteHeaderContents(System.Xml.XmlDictionaryWriter writer, MessageVersion messageVersion)
		{
			writer.WriteRaw(string.Format("<hashValue>{0}</hashValue>", hashValueField));
		}
		  
		public override string Name
		{
			get { return "attachmentHash"; }
		}

		public override string Namespace
		{
			get { return "http://www.caiso.com/mrtu/soa/schemas/2005/09/attachmenthash"; }
		}
	}
}