//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/GasBurnSummaryData_v1.xsd#")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.caiso.com/soa/GasBurnSummaryData_v1.xsd#", IsNullable=false)]
public partial class GasBurnSummaryData {
    
    private MessageHeader messageHeaderField;
    
    private GasBurnSummaryRecord[] messagePayloadField;
    
    /// <remarks/>
    public MessageHeader MessageHeader {
        get {
            return this.messageHeaderField;
        }
        set {
            this.messageHeaderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public GasBurnSummaryRecord[] MessagePayload {
        get {
            return this.messagePayloadField;
        }
        set {
            this.messagePayloadField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/GasBurnSummaryData_v1.xsd#")]
public partial class MessageHeader {
    
    private System.DateTime timeDateField;
    
    private string sourceField;
    
    private string versionField;
    
    public MessageHeader() {
        this.versionField = "v20171001";
    }
    
    /// <remarks/>
    public System.DateTime TimeDate {
        get {
            return this.timeDateField;
        }
        set {
            this.timeDateField = value;
        }
    }
    
    /// <remarks/>
    public string Source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TradeIntervalData))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/GasBurnSummaryData_v1.xsd#")]
public partial class TradeHourData {
    
    private float gasBurnField;
    
    private System.DateTime intervalEndTimeField;
    
    private bool intervalEndTimeFieldSpecified;
    
    private System.DateTime intervalStartTimeField;
    
    /// <remarks/>
    public float gasBurn {
        get {
            return this.gasBurnField;
        }
        set {
            this.gasBurnField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime intervalEndTime {
        get {
            return this.intervalEndTimeField;
        }
        set {
            this.intervalEndTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool intervalEndTimeSpecified {
        get {
            return this.intervalEndTimeFieldSpecified;
        }
        set {
            this.intervalEndTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime intervalStartTime {
        get {
            return this.intervalStartTimeField;
        }
        set {
            this.intervalStartTimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/GasBurnSummaryData_v1.xsd#")]
public partial class TradeIntervalData : TradeHourData {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/GasBurnSummaryData_v1.xsd#")]
public partial class GasZone {
    
    private string nameField;
    
    private GasZoneSummaryLevel summaryLevelField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public GasZoneSummaryLevel summaryLevel {
        get {
            return this.summaryLevelField;
        }
        set {
            this.summaryLevelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/GasBurnSummaryData_v1.xsd#")]
public enum GasZoneSummaryLevel {
    
    /// <remarks/>
    FZONE,
    
    /// <remarks/>
    GASCO,
    
    /// <remarks/>
    GASMTR,
    
    /// <remarks/>
    SAREA,
    
    /// <remarks/>
    TZONE,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(GasBurnSummaryRecord))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/GasBurnSummaryData_v1.xsd#")]
public partial class CMRIReportRecord {
    
    private PTRExecutionType executionTypeField;
    
    private MarketType marketTypeField;
    
    /// <remarks/>
    public PTRExecutionType executionType {
        get {
            return this.executionTypeField;
        }
        set {
            this.executionTypeField = value;
        }
    }
    
    /// <remarks/>
    public MarketType marketType {
        get {
            return this.marketTypeField;
        }
        set {
            this.marketTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/GasBurnSummaryData_v1.xsd#")]
public enum PTRExecutionType {
    
    /// <remarks/>
    HASP,
    
    /// <remarks/>
    IFM,
    
    /// <remarks/>
    RTD,
    
    /// <remarks/>
    RTUC,
    
    /// <remarks/>
    RUC,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/GasBurnSummaryData_v1.xsd#")]
public enum MarketType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2DA")]
    Item2DA,
    
    /// <remarks/>
    DAM,
    
    /// <remarks/>
    RTM,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/GasBurnSummaryData_v1.xsd#")]
public partial class GasBurnSummaryRecord : CMRIReportRecord {
    
    private string gasCompanyField;
    
    private System.DateTime marketEndTimeField;
    
    private bool marketEndTimeFieldSpecified;
    
    private System.DateTime marketStartTimeField;
    
    private bool marketStartTimeFieldSpecified;
    
    private GasZone gasZoneField;
    
    private TradeIntervalData[] tradeIntervalDataField;
    
    /// <remarks/>
    public string gasCompany {
        get {
            return this.gasCompanyField;
        }
        set {
            this.gasCompanyField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime marketEndTime {
        get {
            return this.marketEndTimeField;
        }
        set {
            this.marketEndTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool marketEndTimeSpecified {
        get {
            return this.marketEndTimeFieldSpecified;
        }
        set {
            this.marketEndTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime marketStartTime {
        get {
            return this.marketStartTimeField;
        }
        set {
            this.marketStartTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool marketStartTimeSpecified {
        get {
            return this.marketStartTimeFieldSpecified;
        }
        set {
            this.marketStartTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public GasZone GasZone {
        get {
            return this.gasZoneField;
        }
        set {
            this.gasZoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TradeIntervalData")]
    public TradeIntervalData[] TradeIntervalData {
        get {
            return this.tradeIntervalDataField;
        }
        set {
            this.tradeIntervalDataField = value;
        }
    }
}
