//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyElectricityPriceIndex.electricity {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/2006-06-13/StandardOutput.xsd")]
    public partial class EventLog : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string typeField;
        
        private System.DateTime creationTimeField;
        
        private bool creationTimeFieldSpecified;
        
        private string collectionTypeField;
        
        private string collectionQuantityField;
        
        private Event[] eventField;
        
        private Service[] serviceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime creationTime {
            get {
                return this.creationTimeField;
            }
            set {
                this.creationTimeField = value;
                this.RaisePropertyChanged("creationTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creationTimeSpecified {
            get {
                return this.creationTimeFieldSpecified;
            }
            set {
                this.creationTimeFieldSpecified = value;
                this.RaisePropertyChanged("creationTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string collectionType {
            get {
                return this.collectionTypeField;
            }
            set {
                this.collectionTypeField = value;
                this.RaisePropertyChanged("collectionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string collectionQuantity {
            get {
                return this.collectionQuantityField;
            }
            set {
                this.collectionQuantityField = value;
                this.RaisePropertyChanged("collectionQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Event", Order=7)]
        public Event[] Event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
                this.RaisePropertyChanged("Event");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Service", Order=8)]
        public Service[] Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
                this.RaisePropertyChanged("Service");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/2006-06-13/StandardOutput.xsd")]
    public partial class Event : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string idField;
        
        private string nameField;
        
        private string descriptionField;
        
        private System.DateTime creationTimeField;
        
        private bool creationTimeFieldSpecified;
        
        private string severityField;
        
        private string priorityField;
        
        private string sequenceNumberField;
        
        private string eventTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime creationTime {
            get {
                return this.creationTimeField;
            }
            set {
                this.creationTimeField = value;
                this.RaisePropertyChanged("creationTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creationTimeSpecified {
            get {
                return this.creationTimeFieldSpecified;
            }
            set {
                this.creationTimeFieldSpecified = value;
                this.RaisePropertyChanged("creationTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
                this.RaisePropertyChanged("priority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string sequenceNumber {
            get {
                return this.sequenceNumberField;
            }
            set {
                this.sequenceNumberField = value;
                this.RaisePropertyChanged("sequenceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string eventType {
            get {
                return this.eventTypeField;
            }
            set {
                this.eventTypeField = value;
                this.RaisePropertyChanged("eventType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/2006-06-13/StandardOutput.xsd")]
    public partial class Service : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string commentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
                this.RaisePropertyChanged("comments");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/RequestDailyElectricityPriceIndex_v1.xsd#")]
    public partial class SchedulingCoordinatorList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string schedulingCoordinatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string schedulingCoordinator {
            get {
                return this.schedulingCoordinatorField;
            }
            set {
                this.schedulingCoordinatorField = value;
                this.RaisePropertyChanged("schedulingCoordinator");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/RequestDailyElectricityPriceIndex_v1.xsd#")]
    public partial class ResourceList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resourceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string resource {
            get {
                return this.resourceField;
            }
            set {
                this.resourceField = value;
                this.RaisePropertyChanged("resource");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/RequestDailyElectricityPriceIndex_v1.xsd#")]
    public partial class RequestDailyElectricityPriceIndexRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dateTimeEndField;
        
        private System.DateTime dateTimeStartField;
        
        private MarketType marketTypeField;
        
        private ResourceList[] resourceListField;
        
        private SchedulingCoordinatorList[] schedulingCoordinatorListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime dateTimeEnd {
            get {
                return this.dateTimeEndField;
            }
            set {
                this.dateTimeEndField = value;
                this.RaisePropertyChanged("dateTimeEnd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime dateTimeStart {
            get {
                return this.dateTimeStartField;
            }
            set {
                this.dateTimeStartField = value;
                this.RaisePropertyChanged("dateTimeStart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public MarketType marketType {
            get {
                return this.marketTypeField;
            }
            set {
                this.marketTypeField = value;
                this.RaisePropertyChanged("marketType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ResourceList", Order=3)]
        public ResourceList[] ResourceList {
            get {
                return this.resourceListField;
            }
            set {
                this.resourceListField = value;
                this.RaisePropertyChanged("ResourceList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SchedulingCoordinatorList", Order=4)]
        public SchedulingCoordinatorList[] SchedulingCoordinatorList {
            get {
                return this.schedulingCoordinatorListField;
            }
            set {
                this.schedulingCoordinatorListField = value;
                this.RaisePropertyChanged("SchedulingCoordinatorList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/RequestDailyElectricityPriceIndex_v1.xsd#")]
    public enum MarketType {
        
        /// <remarks/>
        DAM,
        
        /// <remarks/>
        RTM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/RequestDailyElectricityPriceIndex_v1.xsd#")]
    public partial class MessagePayload : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestDailyElectricityPriceIndexRecord requestDailyElectricityPriceIndexRecordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RequestDailyElectricityPriceIndexRecord RequestDailyElectricityPriceIndexRecord {
            get {
                return this.requestDailyElectricityPriceIndexRecordField;
            }
            set {
                this.requestDailyElectricityPriceIndexRecordField = value;
                this.RaisePropertyChanged("RequestDailyElectricityPriceIndexRecord");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/RequestDailyElectricityPriceIndex_v1.xsd#")]
    public partial class MessageHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime timeDateField;
        
        private string sourceField;
        
        private string versionField;
        
        public MessageHeader() {
            this.versionField = "v20171001";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime TimeDate {
            get {
                return this.timeDateField;
            }
            set {
                this.timeDateField = value;
                this.RaisePropertyChanged("TimeDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/RequestDailyElectricityPriceIndex_v1.xsd#")]
    public partial class RequestDailyElectricityPriceIndex : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageHeader messageHeaderField;
        
        private MessagePayload messagePayloadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageHeader MessageHeader {
            get {
                return this.messageHeaderField;
            }
            set {
                this.messageHeaderField = value;
                this.RaisePropertyChanged("MessageHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MessagePayload MessagePayload {
            get {
                return this.messagePayloadField;
            }
            set {
                this.messagePayloadField = value;
                this.RaisePropertyChanged("MessagePayload");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.caiso.com/soa/retrieveDailyElectricityPriceIndex_v1_DocAttach.wsdl", ConfigurationName="electricity.retrieveDailyElectricityPriceIndex_v1_DocAttach")]
    public interface retrieveDailyElectricityPriceIndex_v1_DocAttach {
        
        // CODEGEN: Generating message contract since the operation retrieveDailyElectricityPriceIndex_v1_DocAttach is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.caiso.com/soa/retrieveDailyElectricityPriceIndex_v1_DocAttach", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DailyElectricityPriceIndex.electricity.EventLog[]), Action="http://www.caiso.com/soa/retrieveDailyElectricityPriceIndex_v1_DocAttach", Name="outputDataType", Namespace="http://www.caiso.com/soa/2006-06-13/StandardOutput.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DailyElectricityPriceIndex.electricity.retrieveDailyElectricityPriceIndex_v1_DocAttachResponse retrieveDailyElectricityPriceIndex_v1_DocAttach(DailyElectricityPriceIndex.electricity.retrieveDailyElectricityPriceIndex_v1_DocAttachRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.caiso.com/soa/retrieveDailyElectricityPriceIndex_v1_DocAttach", ReplyAction="*")]
        System.Threading.Tasks.Task<DailyElectricityPriceIndex.electricity.retrieveDailyElectricityPriceIndex_v1_DocAttachResponse> retrieveDailyElectricityPriceIndex_v1_DocAttachAsync(DailyElectricityPriceIndex.electricity.retrieveDailyElectricityPriceIndex_v1_DocAttachRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/2006-06-13/StandardAttachmentInfor.xsd")]
    public partial class Attachment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string versionField;
        
        private string sequenceNumberField;
        
        private string typeField;
        
        private string sizeField;
        
        private string sourceField;
        
        private string toolField;
        
        private System.DateTime creationTimeField;
        
        private bool creationTimeFieldSpecified;
        
        private compressFlag compressFlagField;
        
        private bool compressFlagFieldSpecified;
        
        private string compressMethodField;
        
        private AttributeList[] attributeListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sequenceNumber {
            get {
                return this.sequenceNumberField;
            }
            set {
                this.sequenceNumberField = value;
                this.RaisePropertyChanged("sequenceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("size");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string tool {
            get {
                return this.toolField;
            }
            set {
                this.toolField = value;
                this.RaisePropertyChanged("tool");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime creationTime {
            get {
                return this.creationTimeField;
            }
            set {
                this.creationTimeField = value;
                this.RaisePropertyChanged("creationTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creationTimeSpecified {
            get {
                return this.creationTimeFieldSpecified;
            }
            set {
                this.creationTimeFieldSpecified = value;
                this.RaisePropertyChanged("creationTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public compressFlag compressFlag {
            get {
                return this.compressFlagField;
            }
            set {
                this.compressFlagField = value;
                this.RaisePropertyChanged("compressFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool compressFlagSpecified {
            get {
                return this.compressFlagFieldSpecified;
            }
            set {
                this.compressFlagFieldSpecified = value;
                this.RaisePropertyChanged("compressFlagSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string compressMethod {
            get {
                return this.compressMethodField;
            }
            set {
                this.compressMethodField = value;
                this.RaisePropertyChanged("compressMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttributeList", Order=12)]
        public AttributeList[] AttributeList {
            get {
                return this.attributeListField;
            }
            set {
                this.attributeListField = value;
                this.RaisePropertyChanged("AttributeList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/2006-06-13/StandardAttachmentInfor.xsd")]
    public enum compressFlag {
        
        /// <remarks/>
        yes,
        
        /// <remarks/>
        no,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/2006-06-13/StandardAttachmentInfor.xsd")]
    public partial class AttributeList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sequenceField;
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
                this.RaisePropertyChanged("Sequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.caiso.com/soa/2006-10-26/ISOAttachment.xsd")]
    public partial class ISOAttachment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string attachmentValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AttachmentValue {
            get {
                return this.attachmentValueField;
            }
            set {
                this.attachmentValueField = value;
                this.RaisePropertyChanged("AttachmentValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retrieveDailyElectricityPriceIndex_v1_DocAttachRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.caiso.com/soa/RequestDailyElectricityPriceIndex_v1.xsd#", Order=0)]
        public DailyElectricityPriceIndex.electricity.RequestDailyElectricityPriceIndex RequestDailyElectricityPriceIndex;
        
        public retrieveDailyElectricityPriceIndex_v1_DocAttachRequest() {
        }
        
        public retrieveDailyElectricityPriceIndex_v1_DocAttachRequest(DailyElectricityPriceIndex.electricity.RequestDailyElectricityPriceIndex RequestDailyElectricityPriceIndex) {
            this.RequestDailyElectricityPriceIndex = RequestDailyElectricityPriceIndex;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retrieveDailyElectricityPriceIndex_v1_DocAttachResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.caiso.com/soa/2006-06-13/StandardAttachmentInfor.xsd")]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DailyElectricityPriceIndex.electricity.Attachment[] standardAttachmentInfor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.caiso.com/soa/2006-10-26/ISOAttachment.xsd", Order=0)]
        public DailyElectricityPriceIndex.electricity.ISOAttachment ISOAttachment;
        
        public retrieveDailyElectricityPriceIndex_v1_DocAttachResponse() {
        }
        
        public retrieveDailyElectricityPriceIndex_v1_DocAttachResponse(DailyElectricityPriceIndex.electricity.Attachment[] standardAttachmentInfor, DailyElectricityPriceIndex.electricity.ISOAttachment ISOAttachment) {
            this.standardAttachmentInfor = standardAttachmentInfor;
            this.ISOAttachment = ISOAttachment;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface retrieveDailyElectricityPriceIndex_v1_DocAttachChannel : DailyElectricityPriceIndex.electricity.retrieveDailyElectricityPriceIndex_v1_DocAttach, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class retrieveDailyElectricityPriceIndex_v1_DocAttachClient : System.ServiceModel.ClientBase<DailyElectricityPriceIndex.electricity.retrieveDailyElectricityPriceIndex_v1_DocAttach>, DailyElectricityPriceIndex.electricity.retrieveDailyElectricityPriceIndex_v1_DocAttach {
        
        public retrieveDailyElectricityPriceIndex_v1_DocAttachClient() {
        }
        
        public retrieveDailyElectricityPriceIndex_v1_DocAttachClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public retrieveDailyElectricityPriceIndex_v1_DocAttachClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public retrieveDailyElectricityPriceIndex_v1_DocAttachClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public retrieveDailyElectricityPriceIndex_v1_DocAttachClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DailyElectricityPriceIndex.electricity.retrieveDailyElectricityPriceIndex_v1_DocAttachResponse DailyElectricityPriceIndex.electricity.retrieveDailyElectricityPriceIndex_v1_DocAttach.retrieveDailyElectricityPriceIndex_v1_DocAttach(DailyElectricityPriceIndex.electricity.retrieveDailyElectricityPriceIndex_v1_DocAttachRequest request) {
            return base.Channel.retrieveDailyElectricityPriceIndex_v1_DocAttach(request);
        }
        
        public DailyElectricityPriceIndex.electricity.Attachment[] retrieveDailyElectricityPriceIndex_v1_DocAttach(DailyElectricityPriceIndex.electricity.RequestDailyElectricityPriceIndex RequestDailyElectricityPriceIndex, out DailyElectricityPriceIndex.electricity.ISOAttachment ISOAttachment) {
            DailyElectricityPriceIndex.electricity.retrieveDailyElectricityPriceIndex_v1_DocAttachRequest inValue = new DailyElectricityPriceIndex.electricity.retrieveDailyElectricityPriceIndex_v1_DocAttachRequest();
            inValue.RequestDailyElectricityPriceIndex = RequestDailyElectricityPriceIndex;
            DailyElectricityPriceIndex.electricity.retrieveDailyElectricityPriceIndex_v1_DocAttachResponse retVal = ((DailyElectricityPriceIndex.electricity.retrieveDailyElectricityPriceIndex_v1_DocAttach)(this)).retrieveDailyElectricityPriceIndex_v1_DocAttach(inValue);
            ISOAttachment = retVal.ISOAttachment;
            return retVal.standardAttachmentInfor;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DailyElectricityPriceIndex.electricity.retrieveDailyElectricityPriceIndex_v1_DocAttachResponse> DailyElectricityPriceIndex.electricity.retrieveDailyElectricityPriceIndex_v1_DocAttach.retrieveDailyElectricityPriceIndex_v1_DocAttachAsync(DailyElectricityPriceIndex.electricity.retrieveDailyElectricityPriceIndex_v1_DocAttachRequest request) {
            return base.Channel.retrieveDailyElectricityPriceIndex_v1_DocAttachAsync(request);
        }
        
        public System.Threading.Tasks.Task<DailyElectricityPriceIndex.electricity.retrieveDailyElectricityPriceIndex_v1_DocAttachResponse> retrieveDailyElectricityPriceIndex_v1_DocAttachAsync(DailyElectricityPriceIndex.electricity.RequestDailyElectricityPriceIndex RequestDailyElectricityPriceIndex) {
            DailyElectricityPriceIndex.electricity.retrieveDailyElectricityPriceIndex_v1_DocAttachRequest inValue = new DailyElectricityPriceIndex.electricity.retrieveDailyElectricityPriceIndex_v1_DocAttachRequest();
            inValue.RequestDailyElectricityPriceIndex = RequestDailyElectricityPriceIndex;
            return ((DailyElectricityPriceIndex.electricity.retrieveDailyElectricityPriceIndex_v1_DocAttach)(this)).retrieveDailyElectricityPriceIndex_v1_DocAttachAsync(inValue);
        }
    }
}
