//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmriGasBurnResourceData
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/2006-06-13/StandardOutput.xsd")]
    public partial class EventLog
    {
        
        private string idField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string typeField;
        
        private System.DateTime creationTimeField;
        
        private bool creationTimeFieldSpecified;
        
        private string collectionTypeField;
        
        private string collectionQuantityField;
        
        private Event[] eventField;
        
        private Service[] serviceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime creationTime
        {
            get
            {
                return this.creationTimeField;
            }
            set
            {
                this.creationTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creationTimeSpecified
        {
            get
            {
                return this.creationTimeFieldSpecified;
            }
            set
            {
                this.creationTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string collectionType
        {
            get
            {
                return this.collectionTypeField;
            }
            set
            {
                this.collectionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string collectionQuantity
        {
            get
            {
                return this.collectionQuantityField;
            }
            set
            {
                this.collectionQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Event", Order=7)]
        public Event[] Event
        {
            get
            {
                return this.eventField;
            }
            set
            {
                this.eventField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Service", Order=8)]
        public Service[] Service
        {
            get
            {
                return this.serviceField;
            }
            set
            {
                this.serviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/2006-06-13/StandardOutput.xsd")]
    public partial class Event
    {
        
        private string resultField;
        
        private string idField;
        
        private string nameField;
        
        private string descriptionField;
        
        private System.DateTime creationTimeField;
        
        private bool creationTimeFieldSpecified;
        
        private string severityField;
        
        private string priorityField;
        
        private string sequenceNumberField;
        
        private string eventTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime creationTime
        {
            get
            {
                return this.creationTimeField;
            }
            set
            {
                this.creationTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creationTimeSpecified
        {
            get
            {
                return this.creationTimeFieldSpecified;
            }
            set
            {
                this.creationTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string sequenceNumber
        {
            get
            {
                return this.sequenceNumberField;
            }
            set
            {
                this.sequenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string eventType
        {
            get
            {
                return this.eventTypeField;
            }
            set
            {
                this.eventTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/2006-06-13/StandardOutput.xsd")]
    public partial class Service
    {
        
        private string idField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string commentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/RequestGasBurnResourceData_v1.xsd#")]
    public partial class ResourceList
    {
        
        private string resourceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string resource
        {
            get
            {
                return this.resourceField;
            }
            set
            {
                this.resourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/RequestGasBurnResourceData_v1.xsd#")]
    public partial class GasZone
    {
        
        private string nameField;
        
        private GasZoneSummaryLevel summaryLevelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public GasZoneSummaryLevel summaryLevel
        {
            get
            {
                return this.summaryLevelField;
            }
            set
            {
                this.summaryLevelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/RequestGasBurnResourceData_v1.xsd#")]
    public enum GasZoneSummaryLevel
    {
        
        /// <remarks/>
        FZONE,
        
        /// <remarks/>
        GASCO,
        
        /// <remarks/>
        GASMTR,
        
        /// <remarks/>
        SAREA,
        
        /// <remarks/>
        TZONE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/RequestGasBurnResourceData_v1.xsd#")]
    public partial class GasCompanyList
    {
        
        private string gasCompanyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string gasCompany
        {
            get
            {
                return this.gasCompanyField;
            }
            set
            {
                this.gasCompanyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/RequestGasBurnResourceData_v1.xsd#")]
    public partial class RequestGasBurnResourceRecord
    {
        
        private System.DateTime dateTimeEndField;
        
        private System.DateTime dateTimeStartField;
        
        private PTRExecutionType executionTypeField;
        
        private MarketType marketTypeField;
        
        private GasCompanyList[] gasCompanyListField;
        
        private GasZone[] gasZoneListField;
        
        private ResourceList[] resourceListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime dateTimeEnd
        {
            get
            {
                return this.dateTimeEndField;
            }
            set
            {
                this.dateTimeEndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime dateTimeStart
        {
            get
            {
                return this.dateTimeStartField;
            }
            set
            {
                this.dateTimeStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public PTRExecutionType executionType
        {
            get
            {
                return this.executionTypeField;
            }
            set
            {
                this.executionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public MarketType marketType
        {
            get
            {
                return this.marketTypeField;
            }
            set
            {
                this.marketTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GasCompanyList", Order=4)]
        public GasCompanyList[] GasCompanyList
        {
            get
            {
                return this.gasCompanyListField;
            }
            set
            {
                this.gasCompanyListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GasZoneList", Order=5)]
        public GasZone[] GasZoneList
        {
            get
            {
                return this.gasZoneListField;
            }
            set
            {
                this.gasZoneListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ResourceList", Order=6)]
        public ResourceList[] ResourceList
        {
            get
            {
                return this.resourceListField;
            }
            set
            {
                this.resourceListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/RequestGasBurnResourceData_v1.xsd#")]
    public enum PTRExecutionType
    {
        
        /// <remarks/>
        HASP,
        
        /// <remarks/>
        IFM,
        
        /// <remarks/>
        RTD,
        
        /// <remarks/>
        RTUC,
        
        /// <remarks/>
        RUC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/RequestGasBurnResourceData_v1.xsd#")]
    public enum MarketType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2DA")]
        Item2DA,
        
        /// <remarks/>
        DAM,
        
        /// <remarks/>
        RTM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/RequestGasBurnResourceData_v1.xsd#")]
    public partial class MessagePayload
    {
        
        private RequestGasBurnResourceRecord requestGasBurnResourceRecordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RequestGasBurnResourceRecord RequestGasBurnResourceRecord
        {
            get
            {
                return this.requestGasBurnResourceRecordField;
            }
            set
            {
                this.requestGasBurnResourceRecordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/RequestGasBurnResourceData_v1.xsd#")]
    public partial class MessageHeader
    {
        
        private System.DateTime timeDateField;
        
        private string sourceField;
        
        private string versionField;
        
        public MessageHeader()
        {
            this.versionField = "v20171001";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime TimeDate
        {
            get
            {
                return this.timeDateField;
            }
            set
            {
                this.timeDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/RequestGasBurnResourceData_v1.xsd#")]
    public partial class RequestGasBurnResourceData
    {
        
        private MessageHeader messageHeaderField;
        
        private MessagePayload messagePayloadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageHeader MessageHeader
        {
            get
            {
                return this.messageHeaderField;
            }
            set
            {
                this.messageHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MessagePayload MessagePayload
        {
            get
            {
                return this.messagePayloadField;
            }
            set
            {
                this.messagePayloadField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.caiso.com/soa/retrieveGasBurnResourceData_v1_DocAttach.wsdl", ConfigurationName="CmriGasBurnResourceData.retrieveGasBurnResourceData_v1_DocAttach")]
    internal interface retrieveGasBurnResourceData_v1_DocAttach
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.caiso.com/soa/retrieveGasBurnResourceData_v1_DocAttach", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CmriGasBurnResourceData.EventLog[]), Action="http://www.caiso.com/soa/retrieveGasBurnResourceData_v1_DocAttach", Name="outputDataType", Namespace="http://www.caiso.com/soa/2006-06-13/StandardOutput.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CmriGasBurnResourceData.retrieveGasBurnResourceData_v1_DocAttachResponse> retrieveGasBurnResourceData_v1_DocAttachAsync(CmriGasBurnResourceData.retrieveGasBurnResourceData_v1_DocAttachRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/2006-06-13/StandardAttachmentInfor.xsd")]
    public partial class Attachment
    {
        
        private string idField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string versionField;
        
        private string sequenceNumberField;
        
        private string typeField;
        
        private string sizeField;
        
        private string sourceField;
        
        private string toolField;
        
        private System.DateTime creationTimeField;
        
        private bool creationTimeFieldSpecified;
        
        private compressFlag compressFlagField;
        
        private bool compressFlagFieldSpecified;
        
        private string compressMethodField;
        
        private AttributeList[] attributeListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sequenceNumber
        {
            get
            {
                return this.sequenceNumberField;
            }
            set
            {
                this.sequenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string tool
        {
            get
            {
                return this.toolField;
            }
            set
            {
                this.toolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime creationTime
        {
            get
            {
                return this.creationTimeField;
            }
            set
            {
                this.creationTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creationTimeSpecified
        {
            get
            {
                return this.creationTimeFieldSpecified;
            }
            set
            {
                this.creationTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public compressFlag compressFlag
        {
            get
            {
                return this.compressFlagField;
            }
            set
            {
                this.compressFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool compressFlagSpecified
        {
            get
            {
                return this.compressFlagFieldSpecified;
            }
            set
            {
                this.compressFlagFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string compressMethod
        {
            get
            {
                return this.compressMethodField;
            }
            set
            {
                this.compressMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttributeList", Order=12)]
        public AttributeList[] AttributeList
        {
            get
            {
                return this.attributeListField;
            }
            set
            {
                this.attributeListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/2006-06-13/StandardAttachmentInfor.xsd")]
    public enum compressFlag
    {
        
        /// <remarks/>
        yes,
        
        /// <remarks/>
        no,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/2006-06-13/StandardAttachmentInfor.xsd")]
    public partial class AttributeList
    {
        
        private string sequenceField;
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Sequence
        {
            get
            {
                return this.sequenceField;
            }
            set
            {
                this.sequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.caiso.com/soa/2006-10-26/ISOAttachment.xsd")]
    public partial class ISOAttachment
    {
        
        private string attachmentValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AttachmentValue
        {
            get
            {
                return this.attachmentValueField;
            }
            set
            {
                this.attachmentValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class retrieveGasBurnResourceData_v1_DocAttachRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.caiso.com/soa/RequestGasBurnResourceData_v1.xsd#", Order=0)]
        public CmriGasBurnResourceData.RequestGasBurnResourceData RequestGasBurnResourceData;
        
        public retrieveGasBurnResourceData_v1_DocAttachRequest()
        {
        }
        
        public retrieveGasBurnResourceData_v1_DocAttachRequest(CmriGasBurnResourceData.RequestGasBurnResourceData RequestGasBurnResourceData)
        {
            this.RequestGasBurnResourceData = RequestGasBurnResourceData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class retrieveGasBurnResourceData_v1_DocAttachResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.caiso.com/soa/2006-06-13/StandardAttachmentInfor.xsd")]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CmriGasBurnResourceData.Attachment[] standardAttachmentInfor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.caiso.com/soa/2006-10-26/ISOAttachment.xsd", Order=0)]
        public CmriGasBurnResourceData.ISOAttachment ISOAttachment;
        
        public retrieveGasBurnResourceData_v1_DocAttachResponse()
        {
        }
        
        public retrieveGasBurnResourceData_v1_DocAttachResponse(CmriGasBurnResourceData.Attachment[] standardAttachmentInfor, CmriGasBurnResourceData.ISOAttachment ISOAttachment)
        {
            this.standardAttachmentInfor = standardAttachmentInfor;
            this.ISOAttachment = ISOAttachment;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    internal interface retrieveGasBurnResourceData_v1_DocAttachChannel : CmriGasBurnResourceData.retrieveGasBurnResourceData_v1_DocAttach, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    internal partial class retrieveGasBurnResourceData_v1_DocAttachClient : System.ServiceModel.ClientBase<CmriGasBurnResourceData.retrieveGasBurnResourceData_v1_DocAttach>, CmriGasBurnResourceData.retrieveGasBurnResourceData_v1_DocAttach
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public retrieveGasBurnResourceData_v1_DocAttachClient() : 
                base(retrieveGasBurnResourceData_v1_DocAttachClient.GetDefaultBinding(), retrieveGasBurnResourceData_v1_DocAttachClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.retrieveGasBurnResourceData_DocAttachServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public retrieveGasBurnResourceData_v1_DocAttachClient(EndpointConfiguration endpointConfiguration) : 
                base(retrieveGasBurnResourceData_v1_DocAttachClient.GetBindingForEndpoint(endpointConfiguration), retrieveGasBurnResourceData_v1_DocAttachClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public retrieveGasBurnResourceData_v1_DocAttachClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(retrieveGasBurnResourceData_v1_DocAttachClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public retrieveGasBurnResourceData_v1_DocAttachClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(retrieveGasBurnResourceData_v1_DocAttachClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public retrieveGasBurnResourceData_v1_DocAttachClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CmriGasBurnResourceData.retrieveGasBurnResourceData_v1_DocAttachResponse> CmriGasBurnResourceData.retrieveGasBurnResourceData_v1_DocAttach.retrieveGasBurnResourceData_v1_DocAttachAsync(CmriGasBurnResourceData.retrieveGasBurnResourceData_v1_DocAttachRequest request)
        {
            return base.Channel.retrieveGasBurnResourceData_v1_DocAttachAsync(request);
        }
        
        public System.Threading.Tasks.Task<CmriGasBurnResourceData.retrieveGasBurnResourceData_v1_DocAttachResponse> retrieveGasBurnResourceData_v1_DocAttachAsync(CmriGasBurnResourceData.RequestGasBurnResourceData RequestGasBurnResourceData)
        {
            CmriGasBurnResourceData.retrieveGasBurnResourceData_v1_DocAttachRequest inValue = new CmriGasBurnResourceData.retrieveGasBurnResourceData_v1_DocAttachRequest();
            inValue.RequestGasBurnResourceData = RequestGasBurnResourceData;
            return ((CmriGasBurnResourceData.retrieveGasBurnResourceData_v1_DocAttach)(this)).retrieveGasBurnResourceData_v1_DocAttachAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.retrieveGasBurnResourceData_DocAttachServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.retrieveGasBurnResourceData_DocAttachServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://www.caiso.com/soa/retrieveGasBurnResourceData_v1_DocAttach");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return retrieveGasBurnResourceData_v1_DocAttachClient.GetBindingForEndpoint(EndpointConfiguration.retrieveGasBurnResourceData_DocAttachServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return retrieveGasBurnResourceData_v1_DocAttachClient.GetEndpointAddress(EndpointConfiguration.retrieveGasBurnResourceData_DocAttachServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            retrieveGasBurnResourceData_DocAttachServicePort,
        }
    }
}
