//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

namespace CMRItoSharepoint
{

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#", IsNullable = false)]
	public partial class ResourceOutageData
	{

		private MessageHeader messageHeaderField;

		private RegisteredResourceOutage[] messagePayloadField;

		/// <remarks/>
		public MessageHeader MessageHeader
		{
			get
			{
				return this.messageHeaderField;
			}
			set
			{
				this.messageHeaderField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
		public RegisteredResourceOutage[] MessagePayload
		{
			get
			{
				return this.messagePayloadField;
			}
			set
			{
				this.messagePayloadField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class MessageHeader
	{

		private System.DateTime timeDateField;

		private string sourceField;

		private string versionField;

		public MessageHeader()
		{
			this.versionField = "v20141001";
		}

		/// <remarks/>
		public System.DateTime TimeDate
		{
			get
			{
				return this.timeDateField;
			}
			set
			{
				this.timeDateField = value;
			}
		}

		/// <remarks/>
		public string Source
		{
			get
			{
				return this.sourceField;
			}
			set
			{
				this.sourceField = value;
			}
		}

		/// <remarks/>
		public string Version
		{
			get
			{
				return this.versionField;
			}
			set
			{
				this.versionField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class OutagedRegisteredResource_Config
	{

		private Availability[] availabilityField;

		private object[] itemsField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("Availability")]
		public Availability[] Availability
		{
			get
			{
				return this.availabilityField;
			}
			set
			{
				this.availabilityField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("PMinimum", typeof(PMinimum))]
		[System.Xml.Serialization.XmlElementAttribute("RampRateSegment", typeof(RampRateSegment))]
		public object[] Items
		{
			get
			{
				return this.itemsField;
			}
			set
			{
				this.itemsField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class Availability
	{

		private System.DateTime dateTimePointField;

		private YesNo outOfServiceField;

		private bool outOfServiceFieldSpecified;

		private YesNo returnToNetDependableCapacityField;

		private bool returnToNetDependableCapacityFieldSpecified;

		private OutagedRegisteredResource_outage outagedRegisteredResourceField;

		private FloatQuantity pmaxValueField;

		/// <remarks/>
		public System.DateTime dateTimePoint
		{
			get
			{
				return this.dateTimePointField;
			}
			set
			{
				this.dateTimePointField = value;
			}
		}

		/// <remarks/>
		public YesNo outOfService
		{
			get
			{
				return this.outOfServiceField;
			}
			set
			{
				this.outOfServiceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool outOfServiceSpecified
		{
			get
			{
				return this.outOfServiceFieldSpecified;
			}
			set
			{
				this.outOfServiceFieldSpecified = value;
			}
		}

		/// <remarks/>
		public YesNo returnToNetDependableCapacity
		{
			get
			{
				return this.returnToNetDependableCapacityField;
			}
			set
			{
				this.returnToNetDependableCapacityField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool returnToNetDependableCapacitySpecified
		{
			get
			{
				return this.returnToNetDependableCapacityFieldSpecified;
			}
			set
			{
				this.returnToNetDependableCapacityFieldSpecified = value;
			}
		}

		/// <remarks/>
		public OutagedRegisteredResource_outage OutagedRegisteredResource
		{
			get
			{
				return this.outagedRegisteredResourceField;
			}
			set
			{
				this.outagedRegisteredResourceField = value;
			}
		}

		/// <remarks/>
		public FloatQuantity PmaxValue
		{
			get
			{
				return this.pmaxValueField;
			}
			set
			{
				this.pmaxValueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public enum YesNo
	{

		/// <remarks/>
		NO,

		/// <remarks/>
		YES,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class OutagedRegisteredResource_outage
	{

		private RegisteredResourceOutage_outage[] registeredResourceField;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("RegisteredResourceOutage", IsNullable = false)]
		public RegisteredResourceOutage_outage[] RegisteredResource
		{
			get
			{
				return this.registeredResourceField;
			}
			set
			{
				this.registeredResourceField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class RegisteredResourceOutage_outage : Outage_outage
	{
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisteredResourceOutage_outage))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class Outage_outage : Document_mrid
	{
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(Outage_outage))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisteredResourceOutage_outage))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class Document_mrid : IdentifiedObject_mrid
	{
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MktOrganisation))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(Document_mrid))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(Outage_outage))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisteredResourceOutage_outage))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class IdentifiedObject_mrid
	{

		private string mRIDField;

		/// <remarks/>
		public string mRID
		{
			get
			{
				return this.mRIDField;
			}
			set
			{
				this.mRIDField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class MktOrganisation : IdentifiedObject_mrid
	{

		private MarketPerson[] marketPersonField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("MarketPerson")]
		public MarketPerson[] MarketPerson
		{
			get
			{
				return this.marketPersonField;
			}
			set
			{
				this.marketPersonField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class MarketPerson
	{

		private string firstNameField;

		private string lastNameField;

		private TelephoneNumber landlinePhoneField;

		/// <remarks/>
		public string firstName
		{
			get
			{
				return this.firstNameField;
			}
			set
			{
				this.firstNameField = value;
			}
		}

		/// <remarks/>
		public string lastName
		{
			get
			{
				return this.lastNameField;
			}
			set
			{
				this.lastNameField = value;
			}
		}

		/// <remarks/>
		public TelephoneNumber landlinePhone
		{
			get
			{
				return this.landlinePhoneField;
			}
			set
			{
				this.landlinePhoneField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class TelephoneNumber
	{

		private string areaCodeField;

		private string extensionField;

		private string localNumberField;

		/// <remarks/>
		public string areaCode
		{
			get
			{
				return this.areaCodeField;
			}
			set
			{
				this.areaCodeField = value;
			}
		}

		/// <remarks/>
		public string extension
		{
			get
			{
				return this.extensionField;
			}
			set
			{
				this.extensionField = value;
			}
		}

		/// <remarks/>
		public string localNumber
		{
			get
			{
				return this.localNumberField;
			}
			set
			{
				this.localNumberField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class FloatQuantity
	{

		private UnitMultiplier multiplierField;

		private bool multiplierFieldSpecified;

		private FloatQuantityUnit unitField;

		private bool unitFieldSpecified;

		private float valueField;

		/// <remarks/>
		public UnitMultiplier multiplier
		{
			get
			{
				return this.multiplierField;
			}
			set
			{
				this.multiplierField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool multiplierSpecified
		{
			get
			{
				return this.multiplierFieldSpecified;
			}
			set
			{
				this.multiplierFieldSpecified = value;
			}
		}

		/// <remarks/>
		public FloatQuantityUnit unit
		{
			get
			{
				return this.unitField;
			}
			set
			{
				this.unitField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool unitSpecified
		{
			get
			{
				return this.unitFieldSpecified;
			}
			set
			{
				this.unitFieldSpecified = value;
			}
		}

		/// <remarks/>
		public float value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public enum UnitMultiplier
	{

		/// <remarks/>
		M,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public enum FloatQuantityUnit
	{

		/// <remarks/>
		W,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class PMinimum : OperationalUpdatedRating_start
	{
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PMinimum))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MinimumEnergyLimit))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MaximumEnergyLimit))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LoadMinimum))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LoadMaximum))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class OperationalUpdatedRating_start : OperationalRestriction_start
	{
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OperationalUpdatedRating_start))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PMinimum))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MinimumEnergyLimit))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MaximumEnergyLimit))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LoadMinimum))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LoadMaximum))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class OperationalRestriction_start
	{

		private OperationalRestriction_startActivePeriod activePeriodField;

		private FloatQuantity restrictedValueField;

		/// <remarks/>
		public OperationalRestriction_startActivePeriod activePeriod
		{
			get
			{
				return this.activePeriodField;
			}
			set
			{
				this.activePeriodField = value;
			}
		}

		/// <remarks/>
		public FloatQuantity restrictedValue
		{
			get
			{
				return this.restrictedValueField;
			}
			set
			{
				this.restrictedValueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class OperationalRestriction_startActivePeriod
	{

		private System.DateTime startField;

		/// <remarks/>
		public System.DateTime start
		{
			get
			{
				return this.startField;
			}
			set
			{
				this.startField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class MinimumEnergyLimit : OperationalUpdatedRating_start
	{
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class MaximumEnergyLimit : OperationalUpdatedRating_start
	{
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class LoadMinimum : OperationalUpdatedRating_start
	{
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class LoadMaximum : OperationalUpdatedRating_start
	{

		private YesNo outOfServiceField;

		private bool outOfServiceFieldSpecified;

		private YesNo returnToNetDependableCapacityField;

		private bool returnToNetDependableCapacityFieldSpecified;

		/// <remarks/>
		public YesNo outOfService
		{
			get
			{
				return this.outOfServiceField;
			}
			set
			{
				this.outOfServiceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool outOfServiceSpecified
		{
			get
			{
				return this.outOfServiceFieldSpecified;
			}
			set
			{
				this.outOfServiceFieldSpecified = value;
			}
		}

		/// <remarks/>
		public YesNo returnToNetDependableCapacity
		{
			get
			{
				return this.returnToNetDependableCapacityField;
			}
			set
			{
				this.returnToNetDependableCapacityField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool returnToNetDependableCapacitySpecified
		{
			get
			{
				return this.returnToNetDependableCapacityFieldSpecified;
			}
			set
			{
				this.returnToNetDependableCapacityFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class RampRateSegment : OperationalUpdatedRating_value
	{

		private string segmentNumberField;

		private FloatQuantity segmentValueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
		public string segmentNumber
		{
			get
			{
				return this.segmentNumberField;
			}
			set
			{
				this.segmentNumberField = value;
			}
		}

		/// <remarks/>
		public FloatQuantity segmentValue
		{
			get
			{
				return this.segmentValueField;
			}
			set
			{
				this.segmentValueField = value;
			}
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RampRateSegment))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class OperationalUpdatedRating_value : OperationalRestriction_value
	{
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OperationalUpdatedRating_value))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RampRateSegment))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class OperationalRestriction_value
	{

		private FloatQuantity restrictedValueField;

		/// <remarks/>
		public FloatQuantity restrictedValue
		{
			get
			{
				return this.restrictedValueField;
			}
			set
			{
				this.restrictedValueField = value;
			}
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OperationalUpdatedRating_startWh))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(UseLimit))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class OperationalRestriction_startWh
	{

		private OperationalRestriction_startWhActivePeriod activePeriodField;

		private OperationalRestriction_startWhRestrictedValue restrictedValueField;

		/// <remarks/>
		public OperationalRestriction_startWhActivePeriod activePeriod
		{
			get
			{
				return this.activePeriodField;
			}
			set
			{
				this.activePeriodField = value;
			}
		}

		/// <remarks/>
		public OperationalRestriction_startWhRestrictedValue restrictedValue
		{
			get
			{
				return this.restrictedValueField;
			}
			set
			{
				this.restrictedValueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class OperationalRestriction_startWhActivePeriod
	{

		private System.DateTime startField;

		/// <remarks/>
		public System.DateTime start
		{
			get
			{
				return this.startField;
			}
			set
			{
				this.startField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class OperationalRestriction_startWhRestrictedValue
	{

		private UnitMultiplier multiplierField;

		private bool multiplierFieldSpecified;

		private OperationalRestriction_startWhRestrictedValueUnit unitField;

		private bool unitFieldSpecified;

		private float valueField;

		/// <remarks/>
		public UnitMultiplier multiplier
		{
			get
			{
				return this.multiplierField;
			}
			set
			{
				this.multiplierField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool multiplierSpecified
		{
			get
			{
				return this.multiplierFieldSpecified;
			}
			set
			{
				this.multiplierFieldSpecified = value;
			}
		}

		/// <remarks/>
		public OperationalRestriction_startWhRestrictedValueUnit unit
		{
			get
			{
				return this.unitField;
			}
			set
			{
				this.unitField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool unitSpecified
		{
			get
			{
				return this.unitFieldSpecified;
			}
			set
			{
				this.unitFieldSpecified = value;
			}
		}

		/// <remarks/>
		public float value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public enum OperationalRestriction_startWhRestrictedValueUnit
	{

		/// <remarks/>
		Wh,
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(UseLimit))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class OperationalUpdatedRating_startWh : OperationalRestriction_startWh
	{
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class UseLimit : OperationalUpdatedRating_startWh
	{
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class MarketProduct
	{

		private MarketProductType marketProductTypeField;

		/// <remarks/>
		public MarketProductType marketProductType
		{
			get
			{
				return this.marketProductTypeField;
			}
			set
			{
				this.marketProductTypeField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public enum MarketProductType
	{

		/// <remarks/>
		FRD,

		/// <remarks/>
		FRU,

		/// <remarks/>
		NR,

		/// <remarks/>
		RD,

		/// <remarks/>
		RU,

		/// <remarks/>
		SR,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class ASAvailability
	{

		private FloatQuantity availableValueField;

		private MarketProduct marketProductField;

		/// <remarks/>
		public FloatQuantity availableValue
		{
			get
			{
				return this.availableValueField;
			}
			set
			{
				this.availableValueField = value;
			}
		}

		/// <remarks/>
		public MarketProduct MarketProduct
		{
			get
			{
				return this.marketProductField;
			}
			set
			{
				this.marketProductField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class OutagedRegisteredResource
	{

		private UnitStateOnStartUp timeToStartUpField;

		private bool timeToStartUpFieldSpecified;

		private ASAvailability aSAvailabilityField;

		private Availability[] availabilityField;

		private object[] itemsField;

		/// <remarks/>
		public UnitStateOnStartUp timeToStartUp
		{
			get
			{
				return this.timeToStartUpField;
			}
			set
			{
				this.timeToStartUpField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool timeToStartUpSpecified
		{
			get
			{
				return this.timeToStartUpFieldSpecified;
			}
			set
			{
				this.timeToStartUpFieldSpecified = value;
			}
		}

		/// <remarks/>
		public ASAvailability ASAvailability
		{
			get
			{
				return this.aSAvailabilityField;
			}
			set
			{
				this.aSAvailabilityField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("Availability")]
		public Availability[] Availability
		{
			get
			{
				return this.availabilityField;
			}
			set
			{
				this.availabilityField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("LoadMaximum", typeof(LoadMaximum))]
		[System.Xml.Serialization.XmlElementAttribute("LoadMinimum", typeof(LoadMinimum))]
		[System.Xml.Serialization.XmlElementAttribute("MaximumEnergyLimit", typeof(MaximumEnergyLimit))]
		[System.Xml.Serialization.XmlElementAttribute("MinimumEnergyLimit", typeof(MinimumEnergyLimit))]
		[System.Xml.Serialization.XmlElementAttribute("PMinimum", typeof(PMinimum))]
		[System.Xml.Serialization.XmlElementAttribute("RampRateSegment", typeof(RampRateSegment))]
		[System.Xml.Serialization.XmlElementAttribute("UseLimit", typeof(UseLimit))]
		public object[] Items
		{
			get
			{
				return this.itemsField;
			}
			set
			{
				this.itemsField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public enum UnitStateOnStartUp
	{

		/// <remarks/>
		COLD,

		/// <remarks/>
		HOT,

		/// <remarks/>
		WARM,
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PowerSystemResource_Config))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisteredResource_Config))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisteredGenerator_Config))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(Configuration))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PowerSystemResource))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisteredResource_generator))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisteredGenerator))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisteredResource))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisteredLoad))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisteredInterTie))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class IdentifiedObject_REST_mridName
	{

		private string mRIDField;

		private string nameField;

		/// <remarks/>
		public string mRID
		{
			get
			{
				return this.mRIDField;
			}
			set
			{
				this.mRIDField = value;
			}
		}

		/// <remarks/>
		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisteredResource_Config))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisteredGenerator_Config))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(Configuration))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class PowerSystemResource_Config : IdentifiedObject_REST_mridName
	{
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisteredGenerator_Config))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(Configuration))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class RegisteredResource_Config : PowerSystemResource_Config
	{

		private OutagedRegisteredResource_Config outagedRegisteredResourceField;

		/// <remarks/>
		public OutagedRegisteredResource_Config OutagedRegisteredResource
		{
			get
			{
				return this.outagedRegisteredResourceField;
			}
			set
			{
				this.outagedRegisteredResourceField = value;
			}
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(Configuration))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class RegisteredGenerator_Config : RegisteredResource_Config
	{
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class Configuration : RegisteredGenerator_Config
	{
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisteredResource_generator))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisteredGenerator))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisteredResource))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisteredLoad))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisteredInterTie))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class PowerSystemResource : IdentifiedObject_REST_mridName
	{
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisteredGenerator))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class RegisteredResource_generator : PowerSystemResource
	{

		private Configuration[] logicalConfigurationField;

		private OutagedRegisteredResource outagedRegisteredResourceField;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
		public Configuration[] LogicalConfiguration
		{
			get
			{
				return this.logicalConfigurationField;
			}
			set
			{
				this.logicalConfigurationField = value;
			}
		}

		/// <remarks/>
		public OutagedRegisteredResource OutagedRegisteredResource
		{
			get
			{
				return this.outagedRegisteredResourceField;
			}
			set
			{
				this.outagedRegisteredResourceField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class RegisteredGenerator : RegisteredResource_generator
	{
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisteredLoad))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisteredInterTie))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class RegisteredResource : PowerSystemResource
	{

		private OutagedRegisteredResource outagedRegisteredResourceField;

		/// <remarks/>
		public OutagedRegisteredResource OutagedRegisteredResource
		{
			get
			{
				return this.outagedRegisteredResourceField;
			}
			set
			{
				this.outagedRegisteredResourceField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class RegisteredLoad : RegisteredResource
	{
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class RegisteredInterTie : RegisteredResource
	{
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class Work
	{

		private WorkKind kindField;

		/// <remarks/>
		public WorkKind kind
		{
			get
			{
				return this.kindField;
			}
			set
			{
				this.kindField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public enum WorkKind
	{

		/// <remarks/>
		AMBIENT_DUE_TO_TEMP,

		/// <remarks/>
		AMBIENT_NOT_DUE_TO_TEMP,

		/// <remarks/>
		AVR_EXCITER,

		/// <remarks/>
		ENVIRONMENTAL_RESTRICTIONS,

		/// <remarks/>
		ICCP,

		/// <remarks/>
		METERING_TELEMETRY,

		/// <remarks/>
		NEW_GENERATOR_TEST_ENERGY,

		/// <remarks/>
		PLANT_MAINTENANCE,

		/// <remarks/>
		PLANT_TROUBLE,

		/// <remarks/>
		POWER_SYSTEM_STABILIZER,

		/// <remarks/>
		PRE_UNIT_COMMERCIAL_TESTING,

		/// <remarks/>
		RAMP_RATE,

		/// <remarks/>
		RTU_RIG,

		/// <remarks/>
		TRANSITIONAL_LIMITATION,

		/// <remarks/>
		TRANSMISSION_INDUCED,

		/// <remarks/>
		UNIT_CYCLING,

		/// <remarks/>
		UNIT_SUPPORTING_STARTUP,

		/// <remarks/>
		UNIT_TESTING,

		/// <remarks/>
		USE_LIMIT_REACHED,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class OutageChangeRequest
	{

		private OutageChangeRequestAction actionField;

		private OutageChangeRequestActionReason actionReasonField;

		private bool actionReasonFieldSpecified;

		private OutageChangeRequestActionSubType actionSubTypeField;

		private bool actionSubTypeFieldSpecified;

		/// <remarks/>
		public OutageChangeRequestAction action
		{
			get
			{
				return this.actionField;
			}
			set
			{
				this.actionField = value;
			}
		}

		/// <remarks/>
		public OutageChangeRequestActionReason actionReason
		{
			get
			{
				return this.actionReasonField;
			}
			set
			{
				this.actionReasonField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool actionReasonSpecified
		{
			get
			{
				return this.actionReasonFieldSpecified;
			}
			set
			{
				this.actionReasonFieldSpecified = value;
			}
		}

		/// <remarks/>
		public OutageChangeRequestActionSubType actionSubType
		{
			get
			{
				return this.actionSubTypeField;
			}
			set
			{
				this.actionSubTypeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool actionSubTypeSpecified
		{
			get
			{
				return this.actionSubTypeFieldSpecified;
			}
			set
			{
				this.actionSubTypeFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public enum OutageChangeRequestAction
	{

		/// <remarks/>
		CANCEL,

		/// <remarks/>
		UPDATE,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public enum OutageChangeRequestActionReason
	{

		/// <remarks/>
		CANCELLED_BY_CREW_PTO,

		/// <remarks/>
		CANCELLED_BY_CREW_SC,

		/// <remarks/>
		CHANGE_IN_SCOPE_OF_WORK_PTO,

		/// <remarks/>
		CHANGE_IN_SCOPE_OF_WORK_SC,

		/// <remarks/>
		CONFLICT_WITH_RELATED_OUTAGE_ISO,

		/// <remarks/>
		CONFLICT_WITH_RELATED_OUTAGE_PTO,

		/// <remarks/>
		CONFLICT_WITH_RELATED_OUTAGE_SC,

		/// <remarks/>
		CUSTOMER_REQUEST_PTO,

		/// <remarks/>
		CUSTOMER_REQUEST_SC,

		/// <remarks/>
		DUPLICATE_TICKET_ISO,

		/// <remarks/>
		DUPLICATE_TICKET_PTO,

		/// <remarks/>
		DUPLICATE_TICKET_SC,

		/// <remarks/>
		ENDANGERED_HABITAT_PTO,

		/// <remarks/>
		ENDANGERED_HABITAT_SC,

		/// <remarks/>
		EQUIPMENT_NOT_AVAILABLE_PTO,

		/// <remarks/>
		EQUIPMENT_NOT_AVAILABLE_SC,

		/// <remarks/>
		EXTENSION_OF_RELATED_OUTAGE_PTO,

		/// <remarks/>
		EXTENSION_OF_RELATED_OUTAGE_SC,

		/// <remarks/>
		FIRE_AFFECTING_FACILITY_PTO,

		/// <remarks/>
		FIRE_AFFECTING_FACILITY_SC,

		/// <remarks/>
		HIGH_AREA_TEMPERATURES_ISO,

		/// <remarks/>
		HIGH_AREA_TEMPERATURES_PTO,

		/// <remarks/>
		HIGH_AREA_TEMPERATURES_SC,

		/// <remarks/>
		INCLEMENT_WEATHER_ISO,

		/// <remarks/>
		INCLEMENT_WEATHER_PTO,

		/// <remarks/>
		INCLEMENT_WEATHER_SC,

		/// <remarks/>
		INSUFFICIENT_RESOURCES_PTO,

		/// <remarks/>
		INSUFFICIENT_RESOURCES_SC,

		/// <remarks/>
		ISO_NO_TOUCH_DAY_REQUIREMENTS_ISO,

		/// <remarks/>
		ISO_NO_TOUCH_DAY_REQUIREMENTS_PTO,

		/// <remarks/>
		ISO_NO_TOUCH_DAY_REQUIREMENTS_SC,

		/// <remarks/>
		LACK_OF_PERSONNEL_PTO,

		/// <remarks/>
		LACK_OF_PERSONNEL_SC,

		/// <remarks/>
		LATE_NOTIFICATION_AFFECTING_BRANCH_GROUP_ISO,

		/// <remarks/>
		NO_LONGER_NEEDED_PTO,

		/// <remarks/>
		NO_LONGER_NEEDED_SC,

		/// <remarks/>
		OTHER,

		/// <remarks/>
		REQUIRES_FURTHER_STUDY_ISO,

		/// <remarks/>
		REQUIRES_FURTHER_STUDY_PTO,

		/// <remarks/>
		REQUIRES_FURTHER_STUDY_SC,

		/// <remarks/>
		WORK_INCOMPLETE_PTO,

		/// <remarks/>
		WORK_INCOMPLETE_SC,

		/// <remarks/>
		WORK_PREVIOUSLY_COMPLETED_PTO,

		/// <remarks/>
		WORK_PREVIOUSLY_COMPLETED_SC,

		/// <remarks/>
		WORK_RESCHEDULED_TO_EARLIER_DATE_PTO,

		/// <remarks/>
		WORK_RESCHEDULED_TO_EARLIER_DATE_SC,

		/// <remarks/>
		WORK_RESCHEDULED_TO_LATER_DATE_PTO,

		/// <remarks/>
		WORK_RESCHEDULED_TO_LATER_DATE_SC,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public enum OutageChangeRequestActionSubType
	{

		/// <remarks/>
		IN_OK,

		/// <remarks/>
		IN_SERVICE,

		/// <remarks/>
		OUT,

		/// <remarks/>
		OUT_OK,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class OutageCause
	{

		private string codeField;

		/// <remarks/>
		public string code
		{
			get
			{
				return this.codeField;
			}
			set
			{
				this.codeField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class DateTimeInterval
	{

		private System.DateTime endField;

		private bool endFieldSpecified;

		private System.DateTime startField;

		private bool startFieldSpecified;

		/// <remarks/>
		public System.DateTime end
		{
			get
			{
				return this.endField;
			}
			set
			{
				this.endField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool endSpecified
		{
			get
			{
				return this.endFieldSpecified;
			}
			set
			{
				this.endFieldSpecified = value;
			}
		}

		/// <remarks/>
		public System.DateTime start
		{
			get
			{
				return this.startField;
			}
			set
			{
				this.startField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool startSpecified
		{
			get
			{
				return this.startFieldSpecified;
			}
			set
			{
				this.startFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(Document))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(Outage))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisteredResourceOutage))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class IdentifiedObject_mridDesciption
	{

		private string mRIDField;

		private string descriptionField;

		/// <remarks/>
		public string mRID
		{
			get
			{
				return this.mRIDField;
			}
			set
			{
				this.mRIDField = value;
			}
		}

		/// <remarks/>
		public string description
		{
			get
			{
				return this.descriptionField;
			}
			set
			{
				this.descriptionField = value;
			}
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(Outage))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisteredResourceOutage))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class Document : IdentifiedObject_mridDesciption
	{

		private string commentField;

		/// <remarks/>
		public string comment
		{
			get
			{
				return this.commentField;
			}
			set
			{
				this.commentField = value;
			}
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisteredResourceOutage))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class Outage : Document
	{

		private YesNo affectsRASSPSField;

		private bool affectsRASSPSFieldSpecified;

		private System.DateTime discoveryDateTimeField;

		private bool discoveryDateTimeFieldSpecified;

		private string emergencyReturnTimeField;

		private EmergencyReturnTimeKind emergencyReturnTimeTypeField;

		private string mktOrgOutageIDField;

		private YesNo outageCoordinationLongTermPlanningField;

		private bool outageCoordinationLongTermPlanningFieldSpecified;

		private System.DateTime rIMSProjectCommissionDateField;

		private bool rIMSProjectCommissionDateFieldSpecified;

		private YesNo rIMSProjectCompletionField;

		private bool rIMSProjectCompletionFieldSpecified;

		private string rIMSProjectIDField;

		private string rIMSProjectPhaseField;

		private DateTimeInterval actualPeriodField;

		private OutageEstimatedPeriod estimatedPeriodField;

		private MktOrganisation mktOrganisationField;

		private OutageCause[] outageCauseField;

		private OutageChangeRequest outageChangeRequestField;

		private Work workField;

		/// <remarks/>
		public YesNo affectsRASSPS
		{
			get
			{
				return this.affectsRASSPSField;
			}
			set
			{
				this.affectsRASSPSField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool affectsRASSPSSpecified
		{
			get
			{
				return this.affectsRASSPSFieldSpecified;
			}
			set
			{
				this.affectsRASSPSFieldSpecified = value;
			}
		}

		/// <remarks/>
		public System.DateTime discoveryDateTime
		{
			get
			{
				return this.discoveryDateTimeField;
			}
			set
			{
				this.discoveryDateTimeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool discoveryDateTimeSpecified
		{
			get
			{
				return this.discoveryDateTimeFieldSpecified;
			}
			set
			{
				this.discoveryDateTimeFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
		public string emergencyReturnTime
		{
			get
			{
				return this.emergencyReturnTimeField;
			}
			set
			{
				this.emergencyReturnTimeField = value;
			}
		}

		/// <remarks/>
		public EmergencyReturnTimeKind emergencyReturnTimeType
		{
			get
			{
				return this.emergencyReturnTimeTypeField;
			}
			set
			{
				this.emergencyReturnTimeTypeField = value;
			}
		}

		/// <remarks/>
		public string mktOrgOutageID
		{
			get
			{
				return this.mktOrgOutageIDField;
			}
			set
			{
				this.mktOrgOutageIDField = value;
			}
		}

		/// <remarks/>
		public YesNo outageCoordinationLongTermPlanning
		{
			get
			{
				return this.outageCoordinationLongTermPlanningField;
			}
			set
			{
				this.outageCoordinationLongTermPlanningField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool outageCoordinationLongTermPlanningSpecified
		{
			get
			{
				return this.outageCoordinationLongTermPlanningFieldSpecified;
			}
			set
			{
				this.outageCoordinationLongTermPlanningFieldSpecified = value;
			}
		}

		/// <remarks/>
		public System.DateTime RIMSProjectCommissionDate
		{
			get
			{
				return this.rIMSProjectCommissionDateField;
			}
			set
			{
				this.rIMSProjectCommissionDateField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool RIMSProjectCommissionDateSpecified
		{
			get
			{
				return this.rIMSProjectCommissionDateFieldSpecified;
			}
			set
			{
				this.rIMSProjectCommissionDateFieldSpecified = value;
			}
		}

		/// <remarks/>
		public YesNo RIMSProjectCompletion
		{
			get
			{
				return this.rIMSProjectCompletionField;
			}
			set
			{
				this.rIMSProjectCompletionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool RIMSProjectCompletionSpecified
		{
			get
			{
				return this.rIMSProjectCompletionFieldSpecified;
			}
			set
			{
				this.rIMSProjectCompletionFieldSpecified = value;
			}
		}

		/// <remarks/>
		public string RIMSProjectID
		{
			get
			{
				return this.rIMSProjectIDField;
			}
			set
			{
				this.rIMSProjectIDField = value;
			}
		}

		/// <remarks/>
		public string RIMSProjectPhase
		{
			get
			{
				return this.rIMSProjectPhaseField;
			}
			set
			{
				this.rIMSProjectPhaseField = value;
			}
		}

		/// <remarks/>
		public DateTimeInterval actualPeriod
		{
			get
			{
				return this.actualPeriodField;
			}
			set
			{
				this.actualPeriodField = value;
			}
		}

		/// <remarks/>
		public OutageEstimatedPeriod estimatedPeriod
		{
			get
			{
				return this.estimatedPeriodField;
			}
			set
			{
				this.estimatedPeriodField = value;
			}
		}

		/// <remarks/>
		public MktOrganisation MktOrganisation
		{
			get
			{
				return this.mktOrganisationField;
			}
			set
			{
				this.mktOrganisationField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("OutageCause")]
		public OutageCause[] OutageCause
		{
			get
			{
				return this.outageCauseField;
			}
			set
			{
				this.outageCauseField = value;
			}
		}

		/// <remarks/>
		public OutageChangeRequest OutageChangeRequest
		{
			get
			{
				return this.outageChangeRequestField;
			}
			set
			{
				this.outageChangeRequestField = value;
			}
		}

		/// <remarks/>
		public Work Work
		{
			get
			{
				return this.workField;
			}
			set
			{
				this.workField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public enum EmergencyReturnTimeKind
	{

		/// <remarks/>
		DAYS,

		/// <remarks/>
		DURATION,

		/// <remarks/>
		HOURS,

		/// <remarks/>
		IMMEDIATE,

		/// <remarks/>
		MINUTES,

		/// <remarks/>
		YEARS,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class OutageEstimatedPeriod
	{

		private System.DateTime endField;

		private System.DateTime startField;

		/// <remarks/>
		public System.DateTime end
		{
			get
			{
				return this.endField;
			}
			set
			{
				this.endField = value;
			}
		}

		/// <remarks/>
		public System.DateTime start
		{
			get
			{
				return this.startField;
			}
			set
			{
				this.startField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.caiso.com/soa/ResourceOutageData_v1.xsd#")]
	public partial class RegisteredResourceOutage : Outage
	{

		private YesNo isOffPeakOpportunityOutageField;

		private YesNo isShortNoticeOpportunityOutageField;

		private PowerSystemResource[] itemsField;

		/// <remarks/>
		public YesNo isOffPeakOpportunityOutage
		{
			get
			{
				return this.isOffPeakOpportunityOutageField;
			}
			set
			{
				this.isOffPeakOpportunityOutageField = value;
			}
		}

		/// <remarks/>
		public YesNo isShortNoticeOpportunityOutage
		{
			get
			{
				return this.isShortNoticeOpportunityOutageField;
			}
			set
			{
				this.isShortNoticeOpportunityOutageField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("RegisteredGenerator", typeof(RegisteredGenerator))]
		[System.Xml.Serialization.XmlElementAttribute("RegisteredInterTie", typeof(RegisteredInterTie))]
		[System.Xml.Serialization.XmlElementAttribute("RegisteredLoad", typeof(RegisteredLoad))]
		public PowerSystemResource[] Items
		{
			get
			{
				return this.itemsField;
			}
			set
			{
				this.itemsField = value;
			}
		}
	}
}